services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE=chat_project.settings
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@db:5432/chat_db
      - REDIS_URL=redis://broker:6379/0
    depends_on:
      - db
      - broker
    ports:
      - "8000:8000"
    command: daphne -b 0.0.0.0 -p 8000 chat_project.asgi:application

  worker:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE=chat_project.settings
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@db:5432/chat_db
      - REDIS_URL=redis://broker:6379/0
      - WORKER=1
    depends_on:
      - web
      - broker
      - db
    command: celery -A chat_project worker --loglevel=info

  db:
    image: postgres:15
    restart: always
    x-defang-postgres: true
    environment:
      - POSTGRES_PASSWORD

  broker:
    image: redis:7
    restart: always
    x-defang-redis: true

