services:
  web:
    extends:
      file: compose.yaml
      service: web
    restart: unless-stopped
    build:
      dockerfile: Dockerfile.dev
    environment:
      - DEBUG=1
    volumes:
      - ./app:/app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - migrate

  migrate:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    restart: on-failure
    environment:
      - DJANGO_SETTINGS_MODULE=chat_project.settings
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@db:5432/postgres
      - DJANGO_SECRET_KEY
      - DEBUG=1
    volumes:
      - ./app:/app
    depends_on:
      - db
    command: python manage.py migrate

  worker:
    extends:
      file: compose.yaml
      service: worker
    restart: unless-stopped
    build:
      dockerfile: Dockerfile.dev
    environment:
      - DEBUG=1
    volumes:
      - ./app:/app

  db:
    extends:
      file: compose.yaml
      service: db
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data

  broker:
    extends:
      file: compose.yaml
      service: broker
    restart: unless-stopped
    volumes:
      - broker_data:/data

volumes:
  db_data:
  broker_data:
