services:
  web:
    extends:
      file: compose.yaml
      service: web
    restart: unless-stopped
    build:
      dockerfile: Dockerfile.dev
    environment:
      - DEBUG=1
    volumes:
      - ./app:/app
    command: python manage.py runserver 0.0.0.0:8000

  worker:
    extends:
      file: compose.yaml
      service: worker
    restart: unless-stopped
    build:
      dockerfile: Dockerfile.dev
    environment:
      - DEBUG=1
    volumes:
      - ./app:/app

  db:
    extends:
      file: compose.yaml
      service: db
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  broker:
    extends:
      file: compose.yaml
      service: broker
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - broker_data:/data

volumes:
  db_data:
  broker_data:
